import {
  AlertCircle,
  ArrowBigUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Calendar,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleDot,
  CircleX,
  CloudUpload,
  Command,
  CornerDownLeft,
  Delete,
  Info,
  Maximize,
  Menu,
  Minimize,
  Minus,
  Option,
  Palette,
  Paperclip,
  Pause,
  Pencil,
  Pipette,
  Play,
  Plus,
  RefreshCw,
  Search,
  Space,
  Square,
  SquareMinus,
  Star,
  StarHalf,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  X,
} from 'lucide-vue-next'
import type { IconAliases } from 'vuetify'

/**
 * Iconos que Vuetify pide por su cuenta para sus propios componentes: la flecha
 * de un `VSelect`, el check de un `VCheckbox`, las flechas de paginación, el
 * spinner de carga, los iconos de `VAlert`.
 *
 * Sin este mapa, Vuetify usa sus alias de fábrica, que nombran iconos de
 * Material Design (`mdi-chevron-right` y compañía) y obligan a cargar la fuente
 * `@mdi/font`: 197 KB de hoja y 403 KB de `.woff2` para dibujar unas decenas de
 * glifos. El front operativo pagaba exactamente eso, y su propio verificador de
 * presupuesto lo tenía anotado como deuda.
 *
 * Con este mapa los dos fronts usan **una sola** librería de iconos —Lucide, en
 * componentes— para la aplicación y para Vuetify. No hay webfont, no hay
 * colección que registrar y no sale ni una petición a una CDN de terceros. Un
 * nombre que no exista deja de compilar en vez de dejar un hueco.
 */
export const lucideAliases: IconAliases = {
  collapse: ChevronUp,
  complete: Check,
  cancel: CircleX,
  close: X,
  delete: CircleX,
  clear: CircleX,
  success: CheckCircle2,
  info: Info,
  warning: AlertCircle,
  error: CircleX,
  prev: ChevronLeft,
  next: ChevronRight,
  checkboxOn: CheckSquare,
  checkboxOff: Square,
  checkboxIndeterminate: SquareMinus,
  delimiter: Circle,
  sortAsc: ArrowUp,
  sortDesc: ArrowDown,
  expand: ChevronDown,
  menu: Menu,
  subgroup: ChevronDown,
  dropdown: ChevronDown,
  radioOn: CircleDot,
  radioOff: Circle,
  edit: Pencil,
  ratingEmpty: Star,
  ratingFull: Star,
  ratingHalf: StarHalf,
  loading: RefreshCw,
  first: ChevronsLeft,
  last: ChevronsRight,
  unfold: ChevronsRight,
  file: Paperclip,
  plus: Plus,
  minus: Minus,
  calendar: Calendar,
  treeviewCollapse: ChevronDown,
  treeviewExpand: ChevronRight,
  eyeDropper: Pipette,
  upload: CloudUpload,
  color: Palette,
  command: Command,
  ctrl: ChevronUp,
  space: Space,
  shift: ArrowBigUp,
  alt: Option,
  enter: CornerDownLeft,
  arrowup: ArrowUp,
  arrowdown: ArrowDown,
  arrowleft: ArrowLeft,
  arrowright: ArrowRight,
  backspace: Delete,
  play: Play,
  pause: Pause,
  fullscreen: Maximize,
  fullscreenExit: Minimize,
  volumeHigh: Volume2,
  volumeMedium: Volume1,
  volumeLow: Volume,
  volumeOff: VolumeX,
  search: Search,
}
