/* Mock data para Historia Clínica — modelado a partir de types/domain.ts */

const VET_MOCK_OWNERS = [
  {
    id: '101', name: 'Carla Mendoza Salinas', document: 'CC 1.024.876.301',
    phone: '+57 312 445 7820', email: 'carla.mendoza@gmail.com',
    address: 'Cra 11 #93-45, Bogotá',
  },
  {
    id: '102', name: 'Luis Felipe Paredes', document: 'CC 79.812.443',
    phone: '+57 318 207 1144', email: 'lfparedes@outlook.com',
    address: 'Calle 80 #14-22, Bogotá',
  },
  {
    id: '103', name: 'Andrea Solís Martín', document: 'CC 1.045.882.117',
    phone: '+57 301 884 0067', email: 'asolis@correo.com',
    address: 'Av. Suba #102-15, Bogotá',
  },
  {
    id: '104', name: 'Jorge Vargas Rendón', document: 'CC 80.115.342',
    phone: '+57 314 902 5523', email: 'jvargas.r@gmail.com',
    address: 'Calle 134 #7-30, Bogotá',
  },
  {
    id: '105', name: 'María José Quiñónez', document: 'CC 1.122.404.881',
    phone: '+57 320 671 9912', email: 'mj.quinones@correo.com',
    address: 'Cra 50 #66-12, Medellín',
  },
  {
    id: '106', name: 'Daniel Ospina', document: 'CC 71.554.220',
    phone: '+57 313 100 4488', email: 'dospina@gmail.com',
    address: 'Calle 10 #43-90, Cali',
  },
];

const VET_MOCK_PETS = {
  '101': [
    {
      id: '1001', name: 'Luna', code: 'PET-1001',
      specie: { id: 's2', name: 'Felino' }, breed: { id: 'b2', name: 'Mestizo' },
      gender: 'FEMALE', bod: '2021-03-14', color: 'Atigrada',
      weight: 4.2, weightType: 'KILOGRAMS', ownerId: '101',
      reproductiveState: 'STERILIZED', deceased: false, animalType: 'NONE',
    },
    {
      id: '1002', name: 'Pelusa', code: 'PET-1002',
      specie: { id: 's2', name: 'Felino' }, breed: { id: 'b21', name: 'Persa' },
      gender: 'FEMALE', bod: '2019-06-02', color: 'Blanco',
      weight: 3.6, weightType: 'KILOGRAMS', ownerId: '101',
      reproductiveState: 'STERILIZED', deceased: false, animalType: 'NONE',
    },
  ],
  '102': [
    {
      id: '1003', name: 'Rocco', code: 'PET-1003',
      specie: { id: 's1', name: 'Canino' }, breed: { id: 'b3', name: 'Labrador Retriever' },
      gender: 'MALE', bod: '2018-11-22', color: 'Dorado',
      weight: 32.5, weightType: 'KILOGRAMS', ownerId: '102',
      reproductiveState: 'NO_STERILIZED', deceased: false, animalType: 'NONE',
    },
  ],
  '103': [
    {
      id: '1004', name: 'Mishi', code: 'PET-1004',
      specie: { id: 's2', name: 'Felino' }, breed: { id: 'b2', name: 'Mestizo' },
      gender: 'FEMALE', bod: '2023-04-08', color: 'Negra',
      weight: 2.8, weightType: 'KILOGRAMS', ownerId: '103',
      reproductiveState: 'STERILIZED', deceased: false, animalType: 'NONE',
    },
  ],
  '104': [
    {
      id: '1005', name: 'Toby', code: 'PET-1005',
      specie: { id: 's1', name: 'Canino' }, breed: { id: 'b6', name: 'Golden Retriever' },
      gender: 'MALE', bod: '2014-09-30', color: 'Crema',
      weight: 28.0, weightType: 'KILOGRAMS', ownerId: '104',
      reproductiveState: 'STERILIZED', deceased: false, animalType: 'NONE',
    },
    {
      id: '1006', name: 'Coco', code: 'PET-1006',
      specie: { id: 's1', name: 'Canino' }, breed: { id: 'b7', name: 'Schnauzer' },
      gender: 'MALE', bod: '2020-01-17', color: 'Sal y pimienta',
      weight: 8.4, weightType: 'KILOGRAMS', ownerId: '104',
      reproductiveState: 'NO_STERILIZED', deceased: false, animalType: 'NONE',
    },
  ],
  '105': [
    {
      id: '1007', name: 'Maya', code: 'PET-1007',
      specie: { id: 's1', name: 'Canino' }, breed: { id: 'b8', name: 'Border Collie' },
      gender: 'FEMALE', bod: '2022-07-12', color: 'Blanco y negro',
      weight: 18.0, weightType: 'KILOGRAMS', ownerId: '105',
      reproductiveState: 'STERILIZED', deceased: false, animalType: 'NONE',
    },
  ],
  '106': [
    {
      id: '1008', name: 'Cleo', code: 'PET-1008',
      specie: { id: 's2', name: 'Felino' }, breed: { id: 'b22', name: 'Siamés' },
      gender: 'FEMALE', bod: '2017-02-19', color: 'Crema y café',
      weight: 4.0, weightType: 'KILOGRAMS', ownerId: '106',
      reproductiveState: 'STERILIZED', deceased: false, animalType: 'NONE',
    },
    {
      id: '1009', name: 'Nala', code: 'PET-1009',
      specie: { id: 's2', name: 'Felino' }, breed: { id: 'b23', name: 'Maine Coon' },
      gender: 'FEMALE', bod: '2023-11-05', color: 'Tortuga',
      weight: 3.1, weightType: 'KILOGRAMS', ownerId: '106',
      reproductiveState: 'NO_STERILIZED', deceased: false, animalType: 'NONE',
    },
  ],
};

// Eventos clínicos por mascota (sourceId única por evento)
const VET_MOCK_EVENTS = {
  // Luna (gata, 1001) — historia rica con consulta + procedimientos hijos
  '1001': [
    { sourceId: 9001, eventType: 'CONSULTATION',    eventDate: '2026-05-12', consultationId: 9001, summary: 'Control vacunación anual. Examen físico normal. Peso 4.2 kg.' },
    { sourceId: 9101, eventType: 'VACCINATION',     eventDate: '2026-05-12', consultationId: 9001, summary: 'Triple felina + Leucemia · Lote VT-99221 · Próxima en 12 meses.' },
    { sourceId: 9201, eventType: 'DEWORMING',       eventDate: '2026-05-12', consultationId: 9001, summary: 'Desparasitación interna · Drontal Cat 1 tableta.' },
    { sourceId: 9301, eventType: 'PRESCRIPTION',    eventDate: '2026-05-12', consultationId: 9001, summary: 'Vitaminas — 1 cápsula c/24h x 30 días.' },
    { sourceId: 9002, eventType: 'CONSULTATION',    eventDate: '2025-11-04', consultationId: 9002, summary: 'Consulta por dermatitis en abdomen. Diagnóstico: alergia alimentaria.' },
    { sourceId: 9401, eventType: 'LABORATORY_TEST', eventDate: '2025-11-04', consultationId: 9002, summary: 'Hemograma completo + química sanguínea (8 parámetros).' },
    { sourceId: 9501, eventType: 'PRESCRIPTION',    eventDate: '2025-11-04', consultationId: 9002, summary: 'Cetirizina 5mg, dieta hipoalergénica por 60 días.' },
    { sourceId: 9003, eventType: 'CONSULTATION',    eventDate: '2024-05-10', consultationId: 9003, summary: 'Esterilización — chequeo prequirúrgico. Sin hallazgos relevantes.' },
    { sourceId: 9601, eventType: 'SURGERY',         eventDate: '2024-05-11', consultationId: 9003, summary: 'OVH (ovariohisterectomía) sin complicaciones.' },
    { sourceId: 9701, eventType: 'HOSPITALIZATION', eventDate: '2024-05-11', consultationId: 9003, summary: 'Hospitalización postquirúrgica 24h. Alta médica al día siguiente.' },
    { sourceId: 9102, eventType: 'VACCINATION',     eventDate: '2024-02-08', consultationId: null, summary: 'Refuerzo Antirrábica · Lote AR-44012.' },
  ],
  // Pelusa
  '1002': [
    { sourceId: 9050, eventType: 'CONSULTATION',    eventDate: '2026-04-30', consultationId: 9050, summary: 'Control anual de mantenimiento. Sin novedades.' },
    { sourceId: 9151, eventType: 'VACCINATION',     eventDate: '2026-04-30', consultationId: 9050, summary: 'Triple felina · Lote VT-99440.' },
    { sourceId: 9051, eventType: 'CONSULTATION',    eventDate: '2025-10-18', consultationId: 9051, summary: 'Tos seca de 3 días. Diagnóstico: rinotraqueitis leve.' },
  ],
  // Rocco
  '1003': [
    { sourceId: 9070, eventType: 'CONSULTATION',    eventDate: '2026-05-23', consultationId: 9070, summary: 'Cojera pata posterior derecha. Sospecha de displasia.' },
    { sourceId: 9270, eventType: 'DIAGNOSTIC_IMAGING', eventDate: '2026-05-23', consultationId: 9070, summary: 'Radiografía cadera AP + LL. Diagnóstico: displasia leve.' },
    { sourceId: 9370, eventType: 'PRESCRIPTION',    eventDate: '2026-05-23', consultationId: 9070, summary: 'Meloxicam 1.5mg/ml · 0.1 mg/kg c/24h x 7 días.' },
    { sourceId: 9071, eventType: 'CONSULTATION',    eventDate: '2025-08-04', consultationId: 9071, summary: 'Chequeo rutinario. Peso estable.' },
    { sourceId: 9171, eventType: 'VACCINATION',     eventDate: '2025-08-04', consultationId: 9071, summary: 'Vacuna óctuple · Lote OC-22118.' },
  ],
  // Mishi
  '1004': [
    { sourceId: 9080, eventType: 'CONSULTATION',    eventDate: '2026-05-20', consultationId: 9080, summary: 'Post-op esterilización · retiro de puntos.' },
    { sourceId: 9180, eventType: 'SURGERY',         eventDate: '2026-05-08', consultationId: null, summary: 'OVH electiva sin complicaciones.' },
  ],
  // Toby
  '1005': [
    { sourceId: 9090, eventType: 'CONSULTATION',    eventDate: '2026-05-23', consultationId: 9090, summary: 'Chequeo geriátrico. Inicio de signos de artrosis.' },
    { sourceId: 9290, eventType: 'LABORATORY_TEST', eventDate: '2026-05-23', consultationId: 9090, summary: 'Panel geriátrico completo + uroanálisis.' },
    { sourceId: 9390, eventType: 'PRESCRIPTION',    eventDate: '2026-05-23', consultationId: 9090, summary: 'Condroprotector + omega 3.' },
    { sourceId: 9091, eventType: 'CONSULTATION',    eventDate: '2024-12-11', consultationId: 9091, summary: 'Limpieza dental bajo anestesia.' },
    { sourceId: 9191, eventType: 'SURGERY',         eventDate: '2024-12-11', consultationId: 9091, summary: 'Profilaxis dental con extracciones (3 piezas).' },
  ],
  '1006': [
    { sourceId: 9095, eventType: 'CONSULTATION',    eventDate: '2026-03-02', consultationId: 9095, summary: 'Otitis externa bilateral. Tratamiento tópico.' },
  ],
  '1007': [
    { sourceId: 9096, eventType: 'VACCINATION',     eventDate: '2026-05-01', consultationId: null, summary: 'Refuerzo anual óctuple.' },
  ],
  '1008': [],
  '1009': [
    { sourceId: 9097, eventType: 'CONSULTATION',    eventDate: '2025-12-08', consultationId: 9097, summary: 'Primera vacunación. Examen físico normal.' },
    { sourceId: 9197, eventType: 'VACCINATION',     eventDate: '2025-12-08', consultationId: 9097, summary: 'Triple felina (1ª dosis).' },
  ],
};

// Detalles por evento (sourceId → payload) — sólo los que aparecen en eventos
const VET_MOCK_EVENT_DETAILS = {
  // Consultation 9001
  9001: { type: 'CONSULTATION', consultationType: { name: 'Control vacunación' }, date: '2026-05-12', nextControl: '2027-05-12',
          anamnesis: 'Paciente acude para control anual. Tutora reporta apetito y comportamiento normal.',
          diagnosis: 'Sin patología actual. Esquema vacunal completo.',
          diagnosisPlan: 'Examen físico general. No requiere paraclínicos.',
          therapeuticPlan: 'Vacunación anual + desparasitación + suplemento vitamínico.' },
  9101: { type: 'VACCINATION', vaccinationType: { name: 'Triple felina + Leucemia' }, date: '2026-05-12',
          lot: 'VT-99221', nextVaccination: '2027-05-12', notes: 'Sin reacción adversa observada.',
          consultation: { id: 9001, date: '2026-05-12' } },
  9201: { type: 'DEWORMING', deworming: 'INTERNAL', date: '2026-05-12', lastDeworming: '2025-11-04',
          product: 'Drontal Cat', dosage: '1 tableta', nextControl: '2026-11-12',
          observations: 'Aplicada en consultorio. Bien tolerada.',
          consultation: { id: 9001, date: '2026-05-12' } },
  9301: { type: 'PRESCRIPTION', date: '2026-05-12',
          diagnosis: 'Refuerzo vitamínico anual.',
          observations: 'Iniciar al día siguiente del control.',
          medicaments: [
            { id: 1, name: 'Vitamina ABCD', presentation: 'Cápsula 250mg', quantity: 30, posology: '1 cápsula c/24h vía oral x 30 días' },
          ],
          consultation: { id: 9001, date: '2026-05-12' } },
  // Consultation 9002
  9002: { type: 'CONSULTATION', consultationType: { name: 'Dermatología' }, date: '2025-11-04', nextControl: '2025-12-04',
          anamnesis: 'Prurito abdominal de 2 semanas. Cambió de alimento hace 1 mes.',
          diagnosis: 'Dermatitis alérgica probablemente alimentaria.',
          diagnosisPlan: 'Hemograma + química básica. Dieta de eliminación 60 días.',
          therapeuticPlan: 'Antihistamínico + dieta hipoalergénica.' },
  9401: { type: 'LABORATORY_TEST', testType: { name: 'Hemograma + química sanguínea' }, date: '2025-11-04',
          quantity: 1, diagnosis: 'Eosinofilia leve. Resto normal.',
          consultation: { id: 9002, date: '2025-11-04' } },
  9501: { type: 'PRESCRIPTION', date: '2025-11-04',
          diagnosis: 'Dermatitis alérgica alimentaria.',
          observations: 'Dieta estricta sin cambios por 60 días.',
          medicaments: [
            { id: 1, name: 'Cetirizina', presentation: 'Tableta 5 mg', quantity: 30, posology: '1/2 tableta c/24h vía oral' },
            { id: 2, name: 'Hill\u2019s z/d', presentation: 'Croqueta 1.5kg', quantity: 2, posology: '40g c/12h vía oral por 60 días' },
          ],
          consultation: { id: 9002, date: '2025-11-04' } },
  // Consultation 9003
  9003: { type: 'CONSULTATION', consultationType: { name: 'Prequirúrgico' }, date: '2024-05-10', nextControl: '2024-05-11',
          anamnesis: 'Paciente sana, ayuno cumplido. Apta para cirugía electiva.',
          diagnosis: 'Sin riesgo anestésico aumentado.',
          diagnosisPlan: 'Hemograma + química preoperatoria.',
          therapeuticPlan: 'OVH programada para mañana.' },
  9601: { type: 'SURGERY', surgeryType: { name: 'OVH' }, date: '2024-05-11',
          description: 'Ovariohisterectomía electiva por flanco izquierdo.',
          medicament: 'Acepromacina + ketamina + propofol. Mantenimiento isofluorano.',
          observations: 'Procedimiento de 45 min. Sangrado mínimo.',
          complications: 'Ninguna.',
          consultation: { id: 9003, date: '2024-05-10' } },
  9701: { type: 'HOSPITALIZATION', hospType: 'HOSPITALIZATION', date: '2024-05-11',
          startDate: '2024-05-11', endDate: '2024-05-12',
          reasonLeaving: 'MEDICAL_DISCHARGE',
          reason: 'Observación postquirúrgica OVH.',
          observations: 'Recuperación anestésica normal. Apetito al despertar.',
          consultation: { id: 9003, date: '2024-05-10' } },
  9102: { type: 'VACCINATION', vaccinationType: { name: 'Antirrábica' }, date: '2024-02-08',
          lot: 'AR-44012', nextVaccination: '2025-02-08', notes: 'Refuerzo anual.',
          consultation: null },
  // Pelusa
  9050: { type: 'CONSULTATION', consultationType: { name: 'Control general' }, date: '2026-04-30', nextControl: '2027-04-30',
          anamnesis: 'Control de mantenimiento. Sin reportes de la tutora.',
          diagnosis: 'Paciente sana.',
          diagnosisPlan: 'Examen físico general.',
          therapeuticPlan: 'Vacunación anual.' },
  9151: { type: 'VACCINATION', vaccinationType: { name: 'Triple felina' }, date: '2026-04-30',
          lot: 'VT-99440', nextVaccination: '2027-04-30', notes: '—',
          consultation: { id: 9050, date: '2026-04-30' } },
  9051: { type: 'CONSULTATION', consultationType: { name: 'Respiratoria' }, date: '2025-10-18', nextControl: null,
          anamnesis: 'Tos seca y estornudos de 3 días.',
          diagnosis: 'Rinotraqueitis viral felina leve.',
          diagnosisPlan: 'Examen físico. Auscultación normal.',
          therapeuticPlan: 'Soporte: hidratación, alimento húmedo, vigilancia.' },
  // Rocco
  9070: { type: 'CONSULTATION', consultationType: { name: 'Ortopedia' }, date: '2026-05-23', nextControl: '2026-06-15',
          anamnesis: 'Cojera intermitente de pata posterior derecha hace 3 semanas. Empeora con el ejercicio.',
          diagnosis: 'Displasia coxofemoral leve (grado B).',
          diagnosisPlan: 'Radiografías AP y LL de cadera + ortopédico de control.',
          therapeuticPlan: 'AINE 7 días + control de peso + condroprotectores.' },
  9270: { type: 'DIAGNOSTIC_IMAGING', diagnosticImagingType: { name: 'Radiografía simple' }, date: '2026-05-23',
          studyType: 'Cadera AP + lateral lateral',
          clinicalSigns: 'Cojera posterior derecha, dolor a la extensión.',
          diagnosis: 'Displasia coxofemoral grado B con incongruencia leve.',
          observations: 'Comparativo bilateral. Recomienda RMN si no mejora.',
          consultation: { id: 9070, date: '2026-05-23' } },
  9370: { type: 'PRESCRIPTION', date: '2026-05-23',
          diagnosis: 'Displasia coxofemoral leve.',
          observations: 'Suspender ejercicios de impacto durante el tratamiento.',
          medicaments: [
            { id: 1, name: 'Meloxicam', presentation: 'Suspensión 1.5 mg/ml', quantity: 1, posology: '0.1 mg/kg c/24h vía oral x 7 días' },
          ],
          consultation: { id: 9070, date: '2026-05-23' } },
  9071: { type: 'CONSULTATION', consultationType: { name: 'Control general' }, date: '2025-08-04', nextControl: '2026-08-04',
          anamnesis: 'Chequeo rutinario. Tutor reporta buen estado general.',
          diagnosis: 'Sin hallazgos relevantes.',
          diagnosisPlan: 'Examen físico.',
          therapeuticPlan: 'Vacunación.' },
  9171: { type: 'VACCINATION', vaccinationType: { name: 'Óctuple canina' }, date: '2025-08-04',
          lot: 'OC-22118', nextVaccination: '2026-08-04', notes: '—',
          consultation: { id: 9071, date: '2025-08-04' } },
  // Mishi
  9080: { type: 'CONSULTATION', consultationType: { name: 'Postoperatorio' }, date: '2026-05-20', nextControl: null,
          anamnesis: 'Control de cicatrización. Sin signos de inflamación.',
          diagnosis: 'Cicatrización completa.',
          diagnosisPlan: 'Inspección visual.',
          therapeuticPlan: 'Retiro de suturas.' },
  9180: { type: 'SURGERY', surgeryType: { name: 'OVH' }, date: '2026-05-08',
          description: 'Esterilización electiva por línea media ventral.',
          medicament: 'Premedicación con acepromacina, inducción propofol, mantenimiento isofluorano.',
          observations: 'Procedimiento de 35 min sin complicaciones.',
          complications: 'Ninguna.',
          consultation: null },
  // Toby
  9090: { type: 'CONSULTATION', consultationType: { name: 'Geriátrico' }, date: '2026-05-23', nextControl: '2026-08-23',
          anamnesis: 'Tutor reporta rigidez al levantarse. Apetito disminuido.',
          diagnosis: 'Artrosis incipiente. Función renal en límite alto.',
          diagnosisPlan: 'Panel geriátrico + uroanálisis.',
          therapeuticPlan: 'Condroprotector + omega 3. Dieta senior.' },
  9290: { type: 'LABORATORY_TEST', testType: { name: 'Panel geriátrico + uroanálisis' }, date: '2026-05-23',
          quantity: 1, diagnosis: 'Creatinina 1.6 mg/dL. Resto dentro de rangos.',
          consultation: { id: 9090, date: '2026-05-23' } },
  9390: { type: 'PRESCRIPTION', date: '2026-05-23',
          diagnosis: 'Artrosis incipiente.',
          observations: 'Iniciar con dosis baja por 7 días.',
          medicaments: [
            { id: 1, name: 'Condroitina + Glucosamina', presentation: 'Tableta 500mg', quantity: 60, posology: '1 tableta c/24h vía oral x 60 días' },
            { id: 2, name: 'Omega 3', presentation: 'Cápsula 1000mg', quantity: 60, posology: '1 cápsula c/24h vía oral' },
          ],
          consultation: { id: 9090, date: '2026-05-23' } },
  9091: { type: 'CONSULTATION', consultationType: { name: 'Odontológica' }, date: '2024-12-11', nextControl: '2025-06-11',
          anamnesis: 'Halitosis. Tutor solicita profilaxis.',
          diagnosis: 'Enfermedad periodontal grado 3 con 3 piezas afectadas.',
          diagnosisPlan: 'Profilaxis bajo anestesia + extracciones.',
          therapeuticPlan: 'AB profiláctico 5 días.' },
  9191: { type: 'SURGERY', surgeryType: { name: 'Profilaxis dental' }, date: '2024-12-11',
          description: 'Profilaxis ultrasónica + extracción de 3 piezas con grado 3.',
          medicament: 'Anestesia inhalada isofluorano. Meloxicam intraoperatorio.',
          observations: 'Procedimiento 60 min. Recuperación normal.',
          complications: 'Ninguna.',
          consultation: { id: 9091, date: '2024-12-11' } },
  9095: { type: 'CONSULTATION', consultationType: { name: 'Otitis' }, date: '2026-03-02', nextControl: null,
          anamnesis: 'Rascado constante de orejas y olor.',
          diagnosis: 'Otitis externa bilateral leve.',
          diagnosisPlan: 'Citología de oído.',
          therapeuticPlan: 'Limpieza + tópico tópico c/24h x 10 días.' },
  9096: { type: 'VACCINATION', vaccinationType: { name: 'Óctuple canina (refuerzo)' }, date: '2026-05-01',
          lot: 'OC-23330', nextVaccination: '2027-05-01', notes: '—', consultation: null },
  9097: { type: 'CONSULTATION', consultationType: { name: 'Primera consulta' }, date: '2025-12-08', nextControl: '2025-12-29',
          anamnesis: 'Gatita recién adoptada. Sin antecedentes conocidos.',
          diagnosis: 'Paciente sana. Pendiente esquema vacunal.',
          diagnosisPlan: 'Examen físico.',
          therapeuticPlan: 'Iniciar vacunación.' },
  9197: { type: 'VACCINATION', vaccinationType: { name: 'Triple felina (1ª dosis)' }, date: '2025-12-08',
          lot: 'VT-99001', nextVaccination: '2026-01-08', notes: 'Refuerzo en 30 días.',
          consultation: { id: 9097, date: '2025-12-08' } },
};

Object.assign(window, {
  VET_MOCK_OWNERS, VET_MOCK_PETS, VET_MOCK_EVENTS, VET_MOCK_EVENT_DETAILS,
});
